name: Build Tags
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run GoReleaser
        if: github.ref != 'refs/heads/main'
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
